# Generated by Django 5.0.6 on 2024-07-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(default=None, upload_to='imgs')),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('problem', models.TextField()),
                ('medical_history', models.TextField()),
                ('operation_history', models.TextField()),
                ('other_details', models.TextField()),
                ('contact_no', models.CharField(default='000000000000', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_treatment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=11)),
                ('n_th_treatment', models.IntegerField()),
                ('problem_detial', models.TextField()),
                ('symptoms', models.TextField()),
                ('treatment_given', models.TextField()),
                ('medicine_prescribed', models.TextField()),
                ('fees_charged' , models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees_paid' , models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees_remaining' , models.DecimalField(decimal_places=2, max_digits=10)), 
                ('current_checkup_date', models.DateField()),
                ('next_checkup_date', models.DateField()),
                ('remarks', models.TextField())  
            ],
        ),
    ]
