# Generated by Django 5.0.6 on 2024-08-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_treatment_details',
            old_name='problem_detial',
            new_name='problem_detail',
        ),
    ]
