# Generated by Django 5.0.6 on 2024-09-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0002_rename_problem_detial_patient_treatment_details_problem_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_treatment_details',
            name='fees_charged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient_treatment_details',
            name='fees_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient_treatment_details',
            name='fees_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient_treatment_details',
            name='remarks',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
