# Generated by Django 5.0.6 on 2024-09-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0003_patient_treatment_details_fees_charged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_treatment_details',
            name='fees_charged',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient_treatment_details',
            name='fees_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient_treatment_details',
            name='fees_remaining',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
