# Generated by Django 5.0.6 on 2024-09-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0004_alter_patient_treatment_details_fees_charged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_treatment_details',
            name='extra',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
