# Generated by Django 5.0.6 on 2024-10-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0005_patient_treatment_details_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient_treatment_details',
            name='extra',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
