# Generated by Django 5.0.6 on 2024-10-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0006_remove_patient_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.SmallIntegerField(),
        ),
    ]
