# Generated by Django 5.0.6 on 2024-10-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0010_patient_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_treatment_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=11)),
                ('treatment_id', models.CharField(max_length=12)),
                ('trt_img', models.ImageField(upload_to='treatment_images')),
            ],
        ),
        migrations.AddField(
            model_name='patient_treatment_details',
            name='blood_pressure',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_treatment_details',
            name='oxygen',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_treatment_details',
            name='pulse',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_treatment_details',
            name='vitals_extra',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_treatment_details',
            name='weigth',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
