# Generated by Django 5.0.6 on 2024-10-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0011_patient_treatment_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_treatment_details',
            name='sugar',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
