# Generated by Django 5.0.6 on 2024-10-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0012_patient_treatment_details_sugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_treatment_details',
            name='blood_pressure',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='patient_treatment_details',
            name='oxygen',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='patient_treatment_details',
            name='pulse',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='patient_treatment_details',
            name='sugar',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='patient_treatment_details',
            name='weigth',
            field=models.CharField(max_length=4),
        ),
    ]
